# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import pydantic
from typing import Any, Optional


class Order(pydantic.BaseModel):
    order_id: Any
    user_id: Any
    user_name: Any
    email: Any
    phone: Any
    order_time: Optional[Any]
    status: Any
    shipping_address: Any
