# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import datetime
import pydantic
from typing import Optional


class Order(pydantic.BaseModel):
    order_id: str
    user_id: str
    user_name: str
    email: str
    phone: str
    order_time: Optional[datetime.datetime]
    status: str
    shipping_address: str
