# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: query.sql
import pydantic
from typing import Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from orders.db import models


CREATE_ORDER = """-- name: create_order \\:one
INSERT INTO orders (
  user_id, user_name, email, phone, shipping_address, status, order_id
) VALUES (
  :p1, :p2, :p3, :p4, :p5, :p6, :p7
)
RETURNING order_id, user_id, user_name, email, phone, order_time, status, shipping_address
"""


class CreateOrderParams(pydantic.BaseModel):
    user_id: str
    user_name: str
    email: str
    phone: str
    shipping_address: str
    status: str
    order_id: str


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_order(self, arg: CreateOrderParams) -> Optional[models.Order]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_ORDER), {
            "p1": arg.user_id,
            "p2": arg.user_name,
            "p3": arg.email,
            "p4": arg.phone,
            "p5": arg.shipping_address,
            "p6": arg.status,
            "p7": arg.order_id,
        })).first()
        if row is None:
            return None
        return models.Order(
            order_id=row[0],
            user_id=row[1],
            user_name=row[2],
            email=row[3],
            phone=row[4],
            order_time=row[5],
            status=row[6],
            shipping_address=row[7],
        )
