# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import pydantic
from typing import Any, Optional


class Stock(pydantic.BaseModel):
    id: Any
    item: Any
    available_number: Any
    updated_at: Optional[Any]
