# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import datetime
import pydantic
from typing import Optional


class Stock(pydantic.BaseModel):
    id: int
    item: str
    available_number: int
    updated_at: Optional[datetime.datetime]
