# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import pydantic
from typing import Any, Optional


class Payment(pydantic.BaseModel):
    payment_id: Any
    user_id: Any
    payment_time: Optional[Any]
    status: Any
    method: Any
    amount: Optional[Any]
