# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import datetime
import decimal
import pydantic
from typing import Optional


class Payment(pydantic.BaseModel):
    payment_id: int
    user_id: str
    payment_time: Optional[datetime.datetime]
    status: str
    method: str
    amount: Optional[decimal.Decimal]
